/**
 * src/content.js — контент-данные: кости (RELICS), швы (CURSES), мета-апгрейды (META_UPGRADES), челленджи (CHALLENGES).
 */
export const RELICS = {
  pawn_double: {
    name: 'Длинный шаг',
    enName: 'Long Step',
    desc: 'Пешка может ходить на 1–2 клетки вперёд.',
    enDesc: 'Pawn can move 1–2 cells forward.',
  },
  pawn_omni: {
    name: 'Круговой удар',
    enName: 'Omni Strike',
    desc: 'Пешка бьёт по всем четырём диагоналям (в т.ч. назад).',
    enDesc: 'Pawn attacks all four diagonals (including backward).',
  },
  knight_extra: {
    name: 'Гарцующий конь',
    enName: 'Prancing Knight',
    desc: 'Конь дополнительно может шагнуть на 1 клетку прямо.',
    enDesc: 'Knight may also step 1 cell straight.',
  },
  slider_reach: {
    name: 'Дальний прицел',
    enName: 'Far Sight',
    desc: '+1 к дальности твоих слона, ладьи и ферзя.',
    enDesc: '+1 range to your bishop, rook, and queen.',
  },
  light_lines: {
    name: 'Светлые линии',
    enName: 'Bright Lines',
    desc: 'Стоя на светлой клетке, твои слайдеры бьют на +1 дальше.',
    enDesc: 'Standing on a light square gives your sliders +1 range.',
  },
  no_fatigue: {
    name: 'Ветеран',
    enName: 'Veteran',
    desc: 'Формы больше не устают после взятия.',
    enDesc: 'Forms no longer fatigue after a capture.',
  },
  trophy: {
    name: 'Трофей',
    enName: 'Trophy',
    desc: 'Взятие врага снимает усталость со всех форм.',
    enDesc: 'Killing an enemy removes fatigue from all forms.',
  },
  free_swap: {
    name: 'Быстрые руки',
    enName: 'Quick Hands',
    desc: 'Первая смена формы на каждом этаже бесплатна.',
    enDesc: 'First form swap each floor is free.',
  },
  extra_slot: {
    name: 'Широкое колесо',
    enName: 'Wide Wheel',
    desc: '+1 слот колеса форм.',
    enDesc: '+1 form wheel slot.',
  },
  pawn_shield: {
    name: 'Талисман пешки',
    enName: 'Pawn Talisman',
    desc: 'Один раз за забег взятие в форме пешки не убивает.',
    enDesc: 'Once per run, capture as pawn is not fatal.',
  },
  guard_pierce: {
    name: 'Бронебой',
    enName: 'Piercing',
    desc: 'Твои взятия пробивают броню стража с одного удара.',
    enDesc: 'Your captures pierce Guardian armor in one hit.',
  },
  silence: {
    name: 'Печать тишины',
    enName: 'Seal of Silence',
    desc: 'Некроманты призывают вдвое реже.',
    enDesc: 'Necromancers summon half as often.',
  },
  mirror_break: {
    name: 'Разбитое зеркало',
    enName: 'Shattered Mirror',
    desc: 'Двойники больше не копируют тебя — застревают пешкой.',
    enDesc: 'Mimics no longer copy you — stuck as pawn.',
  },
  smoke: {
    name: 'Дымовая завеса',
    enName: 'Smoke Screen',
    desc: 'Начинаешь каждый этаж со щитом.',
    enDesc: 'Start each floor with a shield.',
  },
  venom: {
    name: 'Ядовитый след',
    enName: 'Venomous Trail',
    desc: 'Враг, взявший тебя, получает яд (гибнет через 2 хода).',
    enDesc: 'Enemy that captures you gets poison (dies in 2 turns).',
  },
  second_wind: {
    name: 'Второе дыхание',
    enName: 'Second Wind',
    desc: 'Начинаешь каждый этаж с ускорением на 2 хода.',
    enDesc: 'Start each floor with haste for 2 turns.',
  },
  concuss: {
    name: 'Ошеломление',
    enName: 'Concussion',
    desc: 'Твоё взятие оглушает врагов рядом с целью на 1 ход.',
    enDesc: 'Your capture stuns enemies adjacent to the target for 1 turn.',
  },
  toxic_aura: {
    name: 'Ядовитая аура',
    enName: 'Toxic Aura',
    desc: 'В начале твоего хода враги вплотную получают яд (1).',
    enDesc: 'At the start of your turn, adjacent enemies get poison (1).',
  },
  bulwark: {
    name: 'Оплот',
    enName: 'Bulwark',
    desc: 'Когда щит гасит взятие, атакующий оглушается.',
    enDesc: 'When shield absorbs a capture, attacker is stunned.',
  },
};
export const CURSES = {
  brittle: {
    name: 'Хрупкость',
    enName: 'Brittle',
    desc: 'Усталость форм длится на 1 ход дольше.',
    enDesc: 'Form fatigue lasts 1 turn longer.',
  },
  heavy: {
    name: 'Тяжёлая поступь',
    enName: 'Heavy Tread',
    desc: '−1 к дальности твоих слона, ладьи и ферзя.',
    enDesc: '−1 range to your bishop, rook, and queen.',
  },
  marked: {
    name: 'Меченый',
    enName: 'Marked',
    desc: 'Слайдеры врагов бьют на 1 клетку дальше.',
    enDesc: 'Enemy sliders hit 1 cell further.',
  },
  compulsion: {
    name: 'Одержимость',
    enName: 'Compulsion',
    desc: 'Нельзя пасовать, пока есть другой ход.',
    enDesc: 'Cannot pass while any other move exists.',
  },
  rusted: {
    name: 'Ржавое колесо',
    enName: 'Rusted Wheel',
    desc: '−1 слот колеса форм (форма в нём теряется).',
    enDesc: '−1 form wheel slot (form in it is lost).',
  },
  bloodline: {
    name: 'Кровавая линия',
    enName: 'Bloodline',
    desc: 'Промоушен закрыт, если на этаже было хоть одно взятие.',
    enDesc: 'Promotion disabled if any capture happened this floor.',
  },
  guard_tough: {
    name: 'Живучая стража',
    enName: 'Tough Guards',
    desc: 'У стражей +1 брони.',
    enDesc: 'Guardians have +1 armor.',
  },
  dark_summon: {
    name: 'Тёмный призыв',
    enName: 'Dark Summon',
    desc: 'Некроманты призывают чаще.',
    enDesc: 'Necromancers summon more often.',
  },
  mimic_reach: {
    name: 'Совершенная копия',
    enName: 'Perfect Copy',
    desc: 'Двойники бьют на клетку дальше.',
    enDesc: 'Mimics gain +1 range.',
  },
  hex: {
    name: 'Порча',
    enName: 'Hex',
    desc: 'Враг, взявший тебя, накладывает яд (2).',
    enDesc: 'Enemy that captures you inflicts poison (2).',
  },
  glass: {
    name: 'Хрупкое тело',
    enName: 'Glass Body',
    desc: 'Щит на тебе не действует.',
    enDesc: 'Shield does not work on you.',
  },
};
export const META_UPGRADES = {
  startSlots: {
    name: 'Наследие форм',
    enName: 'Form Legacy',
    desc: '+1 стартовый слот колеса форм.',
    enDesc: '+1 starting form wheel slot.',
    max: 2,
    costs: [8, 20],
  },
  startRelics: {
    name: 'Расхитительство',
    enName: 'Grave Robbing',
    desc: 'Начинать забег со случайной реликвией.',
    enDesc: 'Start each run with a random relic.',
    max: 2,
    costs: [12, 30],
  },
  headstart: {
    name: 'Разведка',
    enName: 'Reconnaissance',
    desc: 'Первый ярус тише (−2 врага).',
    enDesc: 'First floor is quieter (−2 enemies).',
    max: 1,
    costs: [15],
  },
  archbishop: {
    name: 'Архиепископ',
    enName: 'Archbishop',
    desc: 'Форма «архиепископ» доступна в забегах (слон + конь).',
    enDesc: 'Archbishop form available in runs (bishop + knight).',
    max: 1,
    costs: [12],
  },
  chancellor: {
    name: 'Канцлер',
    enName: 'Chancellor',
    desc: 'Форма «канцлер» доступна в забегах (ладья + конь).',
    enDesc: 'Chancellor form available in runs (rook + knight).',
    max: 1,
    costs: [12],
  },
  beast: {
    name: 'Изверг',
    enName: 'Beast',
    desc: 'Форма «изверг» доступна в забегах (прыжки на 2 в любую сторону).',
    enDesc: 'Beast form available in runs (leaps exactly 2 cells).',
    max: 1,
    costs: [15],
  },
  infiltrator: {
    name: 'Лазутчик',
    enName: 'Infiltrator',
    desc: 'Форма «лазутчик» доступна в забегах (пешка без фасинга, бьёт по всем диагоналям).',
    enDesc: 'Infiltrator form available in runs (facing-free pawn, hits all diagonals).',
    max: 1,
    costs: [14],
  },
  bastion: {
    name: 'Бастион',
    enName: 'Bastion',
    desc: 'Форма «бастион» доступна в забегах (стационарный танк с бронёй).',
    enDesc: 'Bastion form available in runs (stationary tank with armor).',
    max: 1,
    costs: [16],
  },
};
export const CHALLENGES = {
  lone_figure: {
    name: 'Одинокая фигура',
    enName: 'Lone Figure',
    desc: 'Только одна форма на весь забег. Без смены, без деградации. Взятие = конец.',
    enDesc: 'Only one form for the entire run. No switching, no degradation. Capture = end.',
    icon: '🔒',
  },
  blind_descent: {
    name: 'Слепой спуск',
    enName: 'Blind Descent',
    desc: 'Видно только поле в радиусе 2 клеток. Враги и спец-клетки скрыты за пределами обзора.',
    enDesc: 'Only a 2-cell radius is visible. Enemies and special cells are hidden beyond.',
    icon: '🌫️',
  },
  storm: {
    name: 'Шторм',
    enName: 'Storm',
    desc: 'Враги сильнее и быстрее находят тебя. +50% пепла.',
    enDesc: 'Enemies are stronger and find you faster. +50% ash.',
    icon: '⚡',
  },
  chaos_wheel: {
    name: 'Хаотичное колесо',
    enName: 'Chaos Wheel',
    desc: 'Каждые 3 хода форма меняется случайно. Игнорирует усталость.',
    enDesc: 'Every 3 turns, form changes randomly. Ignores fatigue.',
    icon: '🌀',
  },
  escalation: {
    name: 'Эскалация',
    enName: 'Escalation',
    desc: 'С каждым ярусом враги сильнее: +1 дальность, с яруса 5 — броня. ×2 пепла с яруса 5.',
    enDesc: 'Enemies grow stronger each floor: +1 range, armor from floor 5. ×2 ash from floor 5.',
    icon: '💀',
  },
};

export const ACHIEVEMENTS = {
  first_blood: {
    name: 'Первая кровь',
    enName: 'First Blood',
    desc: 'Возьми первого врага.',
    enDesc: 'Take your first enemy.',
  },
  deep: { name: 'Глубоко', enName: 'Deep', desc: 'Достигни 5-го этажа.', enDesc: 'Reach floor 5.' },
  abyss: {
    name: 'Бездна',
    enName: 'Abyss',
    desc: 'Достигни 10-го этажа.',
    enDesc: 'Reach floor 10.',
  },
  collector: {
    name: 'Коллекционер',
    enName: 'Collector',
    desc: 'Собери 5 реликвий за забег.',
    enDesc: 'Collect 5 relics in a run.',
  },
  cursed: {
    name: 'Проклятый',
    enName: 'Cursed',
    desc: 'Прими 3 проклятия за забег.',
    enDesc: 'Accept 3 curses in a run.',
  },
  toxin: {
    name: 'Токсиколог',
    enName: 'Toxicologist',
    desc: 'Убей врага ядом.',
    enDesc: 'Kill an enemy with poison.',
  },
  polymorph: {
    name: 'Полиморф',
    enName: 'Polymorph',
    desc: 'Открой все стандартные формы за забег (пешка, конь, слон, ладья, ферзь).',
    enDesc: 'Unlock all standard forms in a run.',
  },
  bestiary: {
    name: 'Зверолов',
    enName: 'Beastmaster',
    desc: 'Встреть стража, некроманта и двойника.',
    enDesc: 'Meet Guardian, Necromancer, and Mimic.',
  },
  flawless: {
    name: 'Безупречно',
    enName: 'Flawless',
    desc: 'Зачисти этаж, не потеряв ни одной формы.',
    enDesc: 'Clear a floor without losing a form.',
  },
  wealthy: {
    name: 'Богач',
    enName: 'Wealthy',
    desc: 'Накопи 100 пепла.',
    enDesc: 'Accumulate 100 ash.',
  },
  merchant: {
    name: 'Торговец',
    enName: 'Merchant',
    desc: 'Соверши покупку у Костоправа.',
    enDesc: 'Make a purchase at the Bonesetter.',
  },
  pacifist: {
    name: 'Пацифист',
    enName: 'Pacifist',
    desc: 'Пройди этаж без единого взятия.',
    enDesc: 'Clear a floor without a single capture.',
  },
  web_master: {
    name: 'Ловец снов',
    enName: 'Dreamweaver',
    desc: 'Уничтожь 3 врагов паутинами за один забег.',
    enDesc: 'Destroy 3 enemies with webs in one run.',
  },
  arsonist: {
    name: 'Поджигатель',
    enName: 'Arsonist',
    desc: 'Убей врага лавой.',
    enDesc: 'Kill an enemy with lava.',
  },
  speedrun: {
    name: 'Спринтер',
    enName: 'Sprinter',
    desc: 'Зачисти 3 этажа подряд без единого паса.',
    enDesc: 'Clear 3 floors in a row without passing.',
  },
  marathon: {
    name: 'Марафонец',
    enName: 'Marathoner',
    desc: 'Пройди 25 этажей за всё время (суммарно).',
    enDesc: 'Complete 25 floors total across all runs.',
  },
  collector_elite: {
    name: 'Архивариус',
    enName: 'Archivist',
    desc: 'Открой 75% бестиария.',
    enDesc: 'Unlock 75% of the bestiary.',
  },
  architect: {
    name: 'Архитектор',
    enName: 'Architect',
    desc: 'Сыграй забег в каждом из 5 челленджей.',
    enDesc: 'Play a run in each of the 5 challenges.',
  },
  glass_cannon: {
    name: 'Стеклянная пушка',
    enName: 'Glass Cannon',
    desc: 'Дойди до этажа 5+ в челлендже «Одинокая фигура».',
    enDesc: 'Reach floor 5+ in the Lone Figure challenge.',
  },
  storm_chaser: {
    name: 'Охотник за бурей',
    enName: 'Storm Chaser',
    desc: 'Зачисти этаж 7+ в челлендже «Шторм».',
    enDesc: 'Clear floor 7+ in the Storm challenge.',
  },
  kingmaker: {
    name: 'Делатель королей',
    enName: 'Kingmaker',
    desc: 'Доведи пешку до промоушена 3 раза за забег.',
    enDesc: 'Promote a pawn 3 times in one run.',
  },
};
